####################################################
###                                              ###
###                                              ###
###                 VENIX-GROUP                  ###
###            Desenvolvido por: Laas            ###
###          Contato (discord): devlaas          ###
###                 Patch: v1.0                  ###
###                                              ###
###  Sistema de group integrado com [LuckPerms]  ###
###                                              ###
####################################################
###                                              ###
###    Permissão para uso: "venixgroup.group"    ###
###           Dependências: LuckPerms            ###
###                                              ###
###             {PLAYER} = Jogador.              ###
###              {GROUP} = Grupo.                ###
###                {TAG} = Tag.                  ###
###            {MSG} = Chat Message.             ###
###                                              ###
####################################################

database:
  # Database do tipo MYSQL
  # - host, porta, nome da database, usuário, senha.
  host: "localhost"
  port: 3306
  db: "database"
  user: "root"
  pass: ""

# Ao setar o grupo com nome registrado aqui será mostrado um TITLE.
title:
  active: true

  # Configuração do title:
  header: "&6{PLAYER}"
  footer: "&fTornou-se &e{GROUP}&f."

  # Tempo em ticks (20 ticks = 1 segundo)
  fadein: 20 # Tempo para surgir.
  showtime: 60 # Tempo de duração aparente.
  fadeout: 20 # Tempo para esmaecer.

# Insira o nome dos vips registrados em seu LuckPerms.
vips: 
  - vip

tag:
  # Configuração de chat
  enable-chat-format: true
  chat-format: "{TAG}{PLAYER}&7: &f{MSG}"

  # Ao entrar no lobby o sistema irá mandar uma mensagem de entrada referente ao rank do jogador e o mesmo.
  enable-join-lobby: true
  lobbymessage-format: "{TAG}{PLAYER} &6entrou no lobby!"

# Customize as mensagens da forma que você quiser.
messages:
  # Mensagens de erro
  permission: "&c&lERRO: &cVocê não possui permissão para executar esse comando."
  player-error: "&c&lERRO: &cO jogador especificado não foi encontrado em nossa base de dados."
  playerinfo-error: "&c&lERRO: &cOcorreu um erro ao tentar acessar os dados do jogador."
  playergroup-error: "&c&lERRO: &cVocê não pode alterar seu próprio grupo."
  playergroup-has: "&c&lERRO: &cO jogador já possui o grupo &e{GROUP}&c."

  # Mensagens de exito
  playergroup-set: "&6&lGROUP: &fO grupo &e{PLAYER} &ffoi &b&lADICIONADO &fa conta do jogador &a{GROUP}&f."
  playergroup-remove: "&6&lGROUP: &fO grupo &e{PLAYER} &ffoi &c&lREMOVIDO &fda conta do jogador &a{GROUP}&f."

  tag-acess: "&c&lTAG: &cVocê não tem nenhuma tag disponível."
  tag-available: "&c&lTAG: &cAqui estão suas tags disponíveis para uso: \n \n"
  tag-error: "&c&lTAG: &cA tag mencionada é inválida."
  tag-permission: "&c&lTAG: &cVocê não tem permissão para usar essa tag."

  tag-set: "&a&lTAG: §fVocê agora está usando a tag {TAG}§f."

tags: # As tags abaixo representam os grupos disponíveis no seu LuckPerms, então atenção!
  dono:
    name: "&4CEO"
    prefix: "&4&lCEO &4"
    perm: "tag.dono"
    priority: 1
  admin:
    name: "&4Admin"
    prefix: "&4&lADMIN &4"
    perm: "tag.admin"
    priority: 2
  mod+:
    name: "&5Mod+"
    prefix: "&5&lMOD+ &5"
    perm: "tag.modplus"
    priority: 3
  mod:
    name: "&5Mod"
    prefix: "&5&lMOD &5"
    perm: "tag.mod"
    priority: 4
  ajudante:
    name: "&9AJudante"
    prefix: "&9&lAJD &9"
    perm: "tag.helper"
    priority: 5
  vip:
    name: "&aVIP"
    prefix: "&a&lVIP &a"
    perm: "tag.vip"
    priority: 6
  normal:
    name: "&7Normal"
    prefix: "&7&l* &7"
    perm: ""
    priority: 7